version: 1
disable_existing_loggers: no

formatters:
  standard:
    format: "[%(levelname)s] - %(asctime)s - %(message)s"
    datefmt: '%Y-%m-%d,%H:%M'

handlers:
  root_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: camino.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console, root_file_handler]
  propagate: yes